/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'void-black': '#0A0C10',
        'surface-bright': '#36393f',
        'on-background': '#e0e2ea',
        'on-surface-variant': '#c0c7d4',
        'secondary-container': '#414751',
        'surface-container-lowest': '#0b0e14',
        'surface-container': '#1c2025',
        'surface-tint': '#a3c9ff',
        primary: '#a3c9ff',
        'on-surface': '#e0e2ea',
        'slate-silver': '#E2E8F0',
        'plasma-blue': '#007AFF',
        'on-primary': '#00315c',
        'on-error': '#690005',
        'surface-container-low': '#181c21',
        'tertiary-fixed-dim': '#ffba49',
        'secondary-fixed-dim': '#c1c7d2',
        'primary-fixed-dim': '#a3c9ff',
        'primary-container': '#56a5ff',
        tertiary: '#ffba49',
        'tertiary-fixed': '#ffddb1',
        error: '#ffb4ab',
        'on-secondary-fixed-variant': '#414751',
        'on-primary-fixed-variant': '#004882',
        background: '#101419',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d3e4ff',
        'surface-container-highest': '#32353b',
        'on-secondary-fixed': '#161c24',
        'outline-variant': '#414752',
        'surface-dim': '#101419',
        surface: '#101419',
        'on-secondary-container': '#afb5c1',
        'on-primary-container': '#003a6a',
        'on-primary-fixed': '#001c38',
        'error-container': '#93000a',
        'tertiary-container': '#da9400',
        'on-tertiary-fixed-variant': '#624000',
        'surface-variant': '#32353b',
        'glass-stroke': 'rgba(255, 255, 255, 0.12)',
        'on-tertiary': '#442b00',
        'on-secondary': '#2b313a',
        'inverse-primary': '#0060aa',
        secondary: '#c1c7d2',
        'on-tertiary-container': '#4f3300',
        'inverse-surface': '#e0e2ea',
        'inverse-on-surface': '#2d3136',
        'surface-container-high': '#272a30',
        outline: '#8b919d',
        'secondary-fixed': '#dde3ee',
        'on-tertiary-fixed': '#291800',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '24px',
        'stack-lg': '48px',
        gutter: '24px',
        'margin-mobile': '16px',
        'stack-sm': '12px',
        base: '8px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
